### ISSUE TITLE
pls contact xHain

### ISSUE THREAD

**Issue by davedarko** [QubesUsersBerlin/QubesUsersBerlin.github.io#1]
Hello there,

could you or whoever organises the meetups please join the x-Hain matrix chat so you can tell us (or me) when and if this is happening?

Happy new year and talk to you soon hopefully

**Comment by mfc** [comment]
hey dave,
thanks for your interest! today i messaged on the matrix about yesterday, hopefully you saw it. on this page we have a mailing list for the user-group: https://www.autistici.org/mailman/listinfo/qub please join it if you are interested, as folks share availability there so you can have a sense how many folks will show up (if any) for a given meeting, etc.
